// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	GetUnary(ctx context.Context, in *MyUnaryRequest, opts ...grpc.CallOption) (*MyUnaryResponse, error)
	GetStream(ctx context.Context, opts ...grpc.CallOption) (MyService_GetStreamClient, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) GetUnary(ctx context.Context, in *MyUnaryRequest, opts ...grpc.CallOption) (*MyUnaryResponse, error) {
	out := new(MyUnaryResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/GetUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) GetStream(ctx context.Context, opts ...grpc.CallOption) (MyService_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[0], "/pb.MyService/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &myServiceGetStreamClient{stream}
	return x, nil
}

type MyService_GetStreamClient interface {
	Send(*MyStreamRequest) error
	Recv() (*MyStreamResponse, error)
	grpc.ClientStream
}

type myServiceGetStreamClient struct {
	grpc.ClientStream
}

func (x *myServiceGetStreamClient) Send(m *MyStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *myServiceGetStreamClient) Recv() (*MyStreamResponse, error) {
	m := new(MyStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility
type MyServiceServer interface {
	GetUnary(context.Context, *MyUnaryRequest) (*MyUnaryResponse, error)
	GetStream(MyService_GetStreamServer) error
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (UnimplementedMyServiceServer) GetUnary(context.Context, *MyUnaryRequest) (*MyUnaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnary not implemented")
}
func (UnimplementedMyServiceServer) GetStream(MyService_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_GetUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyUnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/GetUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetUnary(ctx, req.(*MyUnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyServiceServer).GetStream(&myServiceGetStreamServer{stream})
}

type MyService_GetStreamServer interface {
	Send(*MyStreamResponse) error
	Recv() (*MyStreamRequest, error)
	grpc.ServerStream
}

type myServiceGetStreamServer struct {
	grpc.ServerStream
}

func (x *myServiceGetStreamServer) Send(m *MyStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *myServiceGetStreamServer) Recv() (*MyStreamRequest, error) {
	m := new(MyStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnary",
			Handler:    _MyService_GetUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _MyService_GetStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "myprotos.proto",
}
