// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: myprotos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyUnaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MyUnaryRequest) Reset() {
	*x = MyUnaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyUnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUnaryRequest) ProtoMessage() {}

func (x *MyUnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUnaryRequest.ProtoReflect.Descriptor instead.
func (*MyUnaryRequest) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{0}
}

func (x *MyUnaryRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MyUnaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MyUnaryResponse) Reset() {
	*x = MyUnaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyUnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUnaryResponse) ProtoMessage() {}

func (x *MyUnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUnaryResponse.ProtoReflect.Descriptor instead.
func (*MyUnaryResponse) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{1}
}

func (x *MyUnaryResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Request
type MyStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MyStreamRequest) Reset() {
	*x = MyStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStreamRequest) ProtoMessage() {}

func (x *MyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStreamRequest.ProtoReflect.Descriptor instead.
func (*MyStreamRequest) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{2}
}

func (x *MyStreamRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type World struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *World) Reset() {
	*x = World{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *World) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*World) ProtoMessage() {}

func (x *World) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use World.ProtoReflect.Descriptor instead.
func (*World) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{3}
}

func (x *World) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{4}
}

func (x *Chunk) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Response
type MyStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*MyStreamResponse_Message
	//	*MyStreamResponse_ServerShutdown
	Event isMyStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *MyStreamResponse) Reset() {
	*x = MyStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStreamResponse) ProtoMessage() {}

func (x *MyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStreamResponse.ProtoReflect.Descriptor instead.
func (*MyStreamResponse) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{5}
}

func (m *MyStreamResponse) GetEvent() isMyStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *MyStreamResponse) GetMessage() *Message {
	if x, ok := x.GetEvent().(*MyStreamResponse_Message); ok {
		return x.Message
	}
	return nil
}

func (x *MyStreamResponse) GetServerShutdown() *MyStreamResponse_Shutdown {
	if x, ok := x.GetEvent().(*MyStreamResponse_ServerShutdown); ok {
		return x.ServerShutdown
	}
	return nil
}

type isMyStreamResponse_Event interface {
	isMyStreamResponse_Event()
}

type MyStreamResponse_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type MyStreamResponse_ServerShutdown struct {
	ServerShutdown *MyStreamResponse_Shutdown `protobuf:"bytes,3,opt,name=server_shutdown,json=serverShutdown,proto3,oneof"`
}

func (*MyStreamResponse_Message) isMyStreamResponse_Event() {}

func (*MyStreamResponse_ServerShutdown) isMyStreamResponse_Event() {}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // TODO Rename update
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MyStreamResponse_Shutdown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MyStreamResponse_Shutdown) Reset() {
	*x = MyStreamResponse_Shutdown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStreamResponse_Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStreamResponse_Shutdown) ProtoMessage() {}

func (x *MyStreamResponse_Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_myprotos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStreamResponse_Shutdown.ProtoReflect.Descriptor instead.
func (*MyStreamResponse_Shutdown) Descriptor() ([]byte, []int) {
	return file_myprotos_proto_rawDescGZIP(), []int{5, 0}
}

var File_myprotos_proto protoreflect.FileDescriptor

var file_myprotos_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x79, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f,
	0x4d, 0x79, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d,
	0x0a, 0x05, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a,
	0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9a, 0x01, 0x0a,
	0x10, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x68, 0x75, 0x74,
	0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x0a, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xc2, 0x01, 0x0a, 0x09, 0x4d,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x55, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x11, 0x5a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myprotos_proto_rawDescOnce sync.Once
	file_myprotos_proto_rawDescData = file_myprotos_proto_rawDesc
)

func file_myprotos_proto_rawDescGZIP() []byte {
	file_myprotos_proto_rawDescOnce.Do(func() {
		file_myprotos_proto_rawDescData = protoimpl.X.CompressGZIP(file_myprotos_proto_rawDescData)
	})
	return file_myprotos_proto_rawDescData
}

var file_myprotos_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_myprotos_proto_goTypes = []interface{}{
	(*MyUnaryRequest)(nil),            // 0: pb.MyUnaryRequest
	(*MyUnaryResponse)(nil),           // 1: pb.MyUnaryResponse
	(*MyStreamRequest)(nil),           // 2: pb.MyStreamRequest
	(*World)(nil),                     // 3: pb.World
	(*Chunk)(nil),                     // 4: pb.Chunk
	(*MyStreamResponse)(nil),          // 5: pb.MyStreamResponse
	(*Message)(nil),                   // 6: pb.Message
	(*MyStreamResponse_Shutdown)(nil), // 7: pb.MyStreamResponse.Shutdown
}
var file_myprotos_proto_depIdxs = []int32{
	6, // 0: pb.MyStreamResponse.message:type_name -> pb.Message
	7, // 1: pb.MyStreamResponse.server_shutdown:type_name -> pb.MyStreamResponse.Shutdown
	0, // 2: pb.MyService.GetUnary:input_type -> pb.MyUnaryRequest
	2, // 3: pb.MyService.GetServerStream:input_type -> pb.MyStreamRequest
	2, // 4: pb.MyService.GetStream:input_type -> pb.MyStreamRequest
	1, // 5: pb.MyService.GetUnary:output_type -> pb.MyUnaryResponse
	5, // 6: pb.MyService.GetServerStream:output_type -> pb.MyStreamResponse
	5, // 7: pb.MyService.GetStream:output_type -> pb.MyStreamResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_myprotos_proto_init() }
func file_myprotos_proto_init() {
	if File_myprotos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myprotos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyUnaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyUnaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*World); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myprotos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStreamResponse_Shutdown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_myprotos_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*MyStreamResponse_Message)(nil),
		(*MyStreamResponse_ServerShutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myprotos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myprotos_proto_goTypes,
		DependencyIndexes: file_myprotos_proto_depIdxs,
		MessageInfos:      file_myprotos_proto_msgTypes,
	}.Build()
	File_myprotos_proto = out.File
	file_myprotos_proto_rawDesc = nil
	file_myprotos_proto_goTypes = nil
	file_myprotos_proto_depIdxs = nil
}
